config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders do
      collection do
        get :unfulfilled
        get :fulfilled
      end
    end
    resources :stocks
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [ :show ]
  resources :products, only: [ :show ]


  get "admin" => "admin#index"
  get "cart" => "carts#show"

  post "checkout" => "checkouts#create"

  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"

  post "stripe_checkout" => "stripe_webhooks#checkout"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_categories = Category.take(4)
  end
end

app/views/home/index.html.erb
<div class="bg-[url('jamon_shop_store.jpeg')] bg-cover bg-no-repeat text-white text-center py-20">
  <h1 class="text-5xl font-bold drop-shadow-sm mb-4"> Little Jamon Shop </h1>
  <p class="text-xl mb-8"> You one stop shop for all your Spanish meats! </p>
</div>
<div class="flex font-serif flex-wrap justify-between mt-8 items-center gap-10">
  <% @main_categories.each do |category| %>
    <%= link_to category_path(category) do %>
      <div class="flex flex-col mb-4 shadow hover:shadow-md rounded">
        <h2 class="text-gray-800 font-medium text-lg text-center my-6"><%= category.name.upcase %></h2>
        <%= category.image.present? ? image_tag(category.image.variant(:small), class: "max-w-lg rounded-b") : image_tag("http://via.placeholder.com/512") %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="bg-white py-10 my-10 border">
  <div class="container mx-auto px-6">
    <h2 class="text-4xl font-bold text-center font-serif text-gray-800 mb-8">Customer Testimonials</h2>
    <div class="flex flex-wrap">
      <%= render TestimonialReviewComponent.new(customer_name: "Oliver", review: "The jamon was delivered quickly and it was even better than I expected!") %>
      <%= render TestimonialReviewComponent.new(customer_name: "Sara Lopez", review: "Their customer service was so helpful in guiding me to the perfect jamon for my needs.") %>
      <%= render TestimonialReviewComponent.new(customer_name: "Oliver", review: "Best selection of Spanish hams online, and at great prices!") %>
    </div>
  </div>
</div>
<div class="bg-gray-500 text-white my-10 text-center py-20">
  <h2 class="text-3xl font-bold mb-6 font-serif">Stay Updated</h2>
  <p class="mb-8">Subscribe to our newsletter for the latest updates and offers.</p>
  <%= form_with url: root_path, method: :post, local: true, class: "flex justify-center" do %>
    <%= email_field_tag :email, nil, placeholder: "Enter your email", class: "p-2 rounded-l text-gray-800" %>
    <%= submit_tag "Subscribe", class: "bg-gray-700 hover:bg-gray-800 cursor-pointer text-white font-bold py-2 px-4 rounded-r" %>
  <% end %>
</div>